version: '3.8'


services:
  app: 
    build: .
    env_file:
      - .env
      - .default
    image: app
    container_name: app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default
    volumes:
      - ./prisma/milestone.db:/app/.output/server/prisma/milestone.db



