version: '3.8'


services:
  app:
    build: .
    # env_file:
    #   - .env
    image: app
    container_name: app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - private
    volumes:
      - ./prisma/milestone.db:/app/.output/server/prisma/milestone.db

  cadddy:
    image: caddy:2.7-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    networks:
      - default
      - private
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  private:
    driver: bridge
