services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - NUXT_PUBLIC_API_BASE=https://milestone.unionrolistes.fr
    image: app
    container_name: app
    restart: always
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.milestone.rule=Host(`milestone.unionrolistes.fr`)"
      - "traefik.http.routers.milestone.entrypoints=websecure"
      - "traefik.http.routers.milestone.tls.certresolver=le"
      - "traefik.http.services.milestone.loadbalancer.server.port=3000"
    volumes:
      - ./prisma/milestone.db:/app/.output/server/prisma/milestone.db

networks:
  traefik-public:
    external: true



