services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - NUXT_PUBLIC_API_BASE=https://milestone.unionrolistes.fr
    image: app
    container_name: app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default
    volumes:
      - ./prisma/milestone.db:/app/.output/server/prisma/milestone.db



